import re


class RiskDetector:
    """
    Deterministic risk and escalation signal detector.

    Account-level signals are derived directly from accounts.json.
    Ticket-level signals are derived directly from ticket metadata
    and ticket text.

    Evidence is always copied from the original ticket and is never
    generated by an LLM.
    """

    CHURN_PATTERNS = [
        r"\bcompetitor\b",
        r"\bcompeting vendor\b",
        r"\bswitch(ing)?\b",
        r"\bleav(e|ing)\b",
        r"\bcancel(lation|led|ing)?\b",
        r"\bnon[- ]?renew\b",
        r"\bchurn\b",
    ]

    ESCALATION_PATTERNS = [
        r"\bescalat(e|ed|ing|ion)\b",
        r"\bmanager\b",
        r"\bmanagement\b",
        r"\bexecutive\b",
        r"\bimmediately\b",
        r"\burgent(ly)?\b",
        r"\basap\b",
        r"\bcritical\b",
    ]

    OPERATIONAL_IMPACT_PATTERNS = [
        r"\bperformance degradation\b",
        r"\bdegraded performance\b",
        r"\bextremely slow\b",
        r"\bseverely slow\b",
        r"\bslow(er|ly)?\b",
        r"\btim(e|ing)?[ -]?out(s|ed|ing)?\b",
        r"\bservice unavailable\b",
        r"\bunavailable\b",
        r"\boutage\b",
        r"\bproduction (issue|impact|failure)\b",
        r"\bblocked\b",
        r"\bblocking\b",
        r"\bunable to\b",
        r"\bcannot\b",
        r"\bfailed\b",
        r"\bfailure\b",
        r"\bdata loss\b",
        r"\blost data\b",
        r"\bbusiness impact\b",
        r"\baffected users?\b",
        r"\busers? affected\b",
    ]

    def detect(
        self,
        account: dict,
        tickets: list[dict],
    ) -> list[dict]:

        risks = []

        # Account-level signals
        risks.extend(self._detect_account_risks(account))

        # Ticket-level signals
        for ticket in tickets:
            risks.extend(self._detect_ticket_risks(ticket))

        return self._deduplicate(risks)

    # ---------------------------------------------------------
    # ACCOUNT RISKS
    # ---------------------------------------------------------

    def _detect_account_risks(self, account: dict) -> list[dict]:
        risks = []

        health_status = account.get("health_status")
        usage_trend = account.get("usage_trend")
        p1_count = account.get("p1_tickets_last_30d", 0)
        escalation_notes = account.get("escalation_notes", [])

        if health_status == "Churning":
            risks.append(
                {
                    "risk_type": "Churn",
                    "severity": "high",
                    "source": "account",
                    "reason": (
                        "Account health status is marked as Churning."
                    ),
                }
            )

        elif health_status == "At Risk":
            risks.append(
                {
                    "risk_type": "Account Health",
                    "severity": "high",
                    "source": "account",
                    "reason": (
                        "Account health status is marked as At Risk."
                    ),
                }
            )

        if usage_trend == "Declining":
            risks.append(
                {
                    "risk_type": "Usage Decline",
                    "severity": "medium",
                    "source": "account",
                    "reason": (
                        "Account usage trend is declining."
                    ),
                }
            )

        elif usage_trend == "Inactive":
            risks.append(
                {
                    "risk_type": "Usage Inactivity",
                    "severity": "medium",
                    "source": "account",
                    "reason": (
                        "Account usage trend is inactive."
                    ),
                }
            )

        if p1_count > 0:
            risks.append(
                {
                    "risk_type": "Critical Incidents",
                    "severity": "high",
                    "source": "account",
                    "reason": (
                        f"Account has {p1_count} P1 ticket(s) "
                        "in the last 30 days."
                    ),
                }
            )

        # Escalation notes are supplied directly by the dataset.
        for note in escalation_notes:

            note_lower = note.lower()

            if any(
                re.search(pattern, note_lower)
                for pattern in self.CHURN_PATTERNS
            ):
                risks.append(
                    {
                        "risk_type": "Churn",
                        "severity": "high",
                        "source": "account",
                        "reason": note,
                    }
                )

        return risks

    # ---------------------------------------------------------
    # TICKET RISKS
    # ---------------------------------------------------------

    def _detect_ticket_risks(
        self,
        ticket: dict,
    ) -> list[dict]:

        risks = []

        body = ticket.get("body", "")
        subject = ticket.get("subject", "")

        searchable_text = f"{subject}\n{body}"
        lower_text = searchable_text.lower()

        # -----------------------------------------------------
        # Priority
        # -----------------------------------------------------

        if ticket.get("urgency") == "P1":

            risks.append(
                self._ticket_risk(
                    ticket=ticket,
                    risk_type="Critical Incident",
                    severity="high",
                    reason="Ticket is classified as P1.",
                )
            )

        elif ticket.get("urgency") == "P2":

            risks.append(
                self._ticket_risk(
                    ticket=ticket,
                    risk_type="High Priority Issue",
                    severity="medium",
                    reason="Ticket is classified as P2.",
                )
            )

        # -----------------------------------------------------
        # Churn
        # -----------------------------------------------------

        churn_match = self._find_match(
            lower_text,
            self.CHURN_PATTERNS,
        )

        if churn_match:

            risks.append(
                self._ticket_risk(
                    ticket=ticket,
                    risk_type="Churn Signal",
                    severity="high",
                    reason=(
                        "Ticket contains language indicating "
                        "possible churn risk."
                    ),
                    match=churn_match,
                )
            )

        # -----------------------------------------------------
        # Escalation
        # -----------------------------------------------------

        escalation_match = self._find_match(
            lower_text,
            self.ESCALATION_PATTERNS,
        )

        if escalation_match:

            risks.append(
                self._ticket_risk(
                    ticket=ticket,
                    risk_type="Escalation Signal",
                    severity="medium",
                    reason=(
                        "Ticket contains escalation-related language."
                    ),
                    match=escalation_match,
                )
            )

        # -----------------------------------------------------
        # Operational impact
        # -----------------------------------------------------

        operational_matches = self._find_all_matches(
            lower_text,
            self.OPERATIONAL_IMPACT_PATTERNS,
        )

        if operational_matches:

            evidence = self._collect_evidence(
                body,
                operational_matches,
            )

            severity = "high" if len(operational_matches) >= 2 else "medium"

            risks.append(
                {
                    "risk_type": "Operational Impact",
                    "severity": severity,
                    "source": "ticket",
                    "ticket_id": ticket.get("ticket_id"),
                    "evidence_quote": evidence,
                    "reason": (
                        "Ticket contains one or more indicators "
                        "of operational impact."
                    ),
                }
            )

        return risks

    # ---------------------------------------------------------
    # MATCHING
    # ---------------------------------------------------------

    @staticmethod
    def _find_match(
        text: str,
        patterns: list[str],
    ):
        for pattern in patterns:

            match = re.search(pattern, text)

            if match:
                return match.group(0)

        return None

    @staticmethod
    def _find_all_matches(
        text: str,
        patterns: list[str],
    ) -> list[str]:

        matches = []

        for pattern in patterns:

            found = re.findall(pattern, text)

            if found:
                matches.append(pattern)

        return matches

    # ---------------------------------------------------------
    # EVIDENCE
    # ---------------------------------------------------------

    @staticmethod
    def _collect_evidence(
        body: str,
        matched_patterns: list[str],
    ) -> str:

        lines = body.splitlines()

        evidence_lines = []

        for line in lines:

            stripped = line.strip()

            if not stripped:
                continue

            lower_line = stripped.lower()

            for pattern in matched_patterns:

                if re.search(pattern, lower_line):

                    evidence_lines.append(stripped)
                    break

        if evidence_lines:
            return " ".join(evidence_lines)

        return body.strip()

    @staticmethod
    def _ticket_risk(
        ticket: dict,
        risk_type: str,
        severity: str,
        reason: str,
        match: str | None = None,
    ) -> dict:

        evidence = ticket.get("body", "")

        if match:

            evidence = RiskDetector._extract_evidence(
                ticket.get("body", ""),
                match,
            )

        return {
            "risk_type": risk_type,
            "severity": severity,
            "source": "ticket",
            "ticket_id": ticket.get("ticket_id"),
            "evidence_quote": evidence,
            "reason": reason,
        }

    @staticmethod
    def _extract_evidence(
        body: str,
        match: str,
    ) -> str:

        lines = body.splitlines()

        for line in lines:

            stripped = line.strip()

            if match.lower() in stripped.lower():
                return stripped

        sentences = re.split(
            r"(?<=[.!?])\s+",
            body,
        )

        for sentence in sentences:

            if match.lower() in sentence.lower():
                return sentence.strip()

        return body.strip()

    # ---------------------------------------------------------
    # DEDUPLICATION
    # ---------------------------------------------------------

    @staticmethod
    def _deduplicate(
        risks: list[dict],
    ) -> list[dict]:

        seen = set()
        unique = []

        for risk in risks:

            key = (
                risk.get("risk_type"),
                risk.get("ticket_id"),
                risk.get("evidence_quote"),
                risk.get("reason"),
            )

            if key in seen:
                continue

            seen.add(key)
            unique.append(risk)

        return unique
